<div class='container text-center'>
	<a href="">Rubicon</a>&nbsp;|&nbsp;
	<a href="">OpenX</a>&nbsp;|&nbsp;
	<a href="">PubMatic</a>&nbsp;|&nbsp;
	<a href="">AdXSeller</a>&nbsp;|&nbsp;
	<a href="">AOL US</a>&nbsp;|&nbsp;
	<a href="">RevContent</a>&nbsp;|&nbsp;
	<a href="">Imonomy</a>&nbsp;|&nbsp;
	<a href="">Zedo</a>&nbsp;|&nbsp;
	<a href="">DFP New</a>&nbsp;|&nbsp;
	<a href="">DFP Old</a>&nbsp;|&nbsp;
	<a href="">AppNexus</a>&nbsp;|&nbsp;
	<a href="">Epom</a>&nbsp;|&nbsp;
	<a href="">Matomy Cedato</a>&nbsp;|&nbsp;
	<a href="">Matomy LKQD</a>&nbsp;|&nbsp;
	<a href="">Amazon Affiliate</a>&nbsp;|&nbsp;
	<a href="">Flipkart Affiliate</a>
	<a href="">VCommission</a>&nbsp;|&nbsp;
	<a href="">FreeWheel</a>&nbsp;|&nbsp;
	<a href="">Tremor</a>&nbsp;|&nbsp;
	<a href="">SpotX</a>&nbsp;|&nbsp;
	<a href="">VertaMedia</a>&nbsp;|&nbsp;
	<a href="">VideoBeat</a>&nbsp;|&nbsp;
	<a href="">TapTica</a>&nbsp;|&nbsp;
	<a href="">Datawrkz RS Reporting</a>&nbsp;|&nbsp;
	<a href="">TeamWorks</a>&nbsp;|&nbsp;
	<a href="">Zoho</a>&nbsp;|&nbsp;
	<a href="">Yashi</a>&nbsp;|&nbsp;
	<a href="">InMobi</a>&nbsp;|&nbsp;
	<a href="">AirPush</a>&nbsp;|&nbsp;
	<a href="">PubOps Tracker</a>&nbsp;|&nbsp;
	<a href="">LvLUp</a>&nbsp;|&nbsp;
	<a href="">Forensiq</a>
</div>